# Generated by Django 5.1.2 on 2024-10-27 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
