# Generated by Django 5.1.2 on 2024-10-27 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='score1',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='profile',
            name='score2',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='profile',
            name='score3',
            field=models.JSONField(default=list),
        ),
    ]
